### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by TheDelus** [brendangooden/datalogic-magellan-dotnet#3]
Hi,
I am having trouble to connect a Scanner/Scale combo using RS232 Single Cable to a PC and found your repo. For me the normal RS232 Interface is working fine and I can communicate with this interface. But I have to use the RS232 Single Cable Interface like you. I receive the label data but can not start the weight measurement. I have 2 questions:

1. I found this in your code. Is it required?
```
            this._serialPort.RtsEnable = true;
            this._serialPort.DtrEnable = true;
```
2. Where did you find the documentation of the command set for the single cable interface?

Greetings and thank you for your work

**Comment by brendangooden** [comment]
Hi @TheDelus 
See attached scanner scale protocol summary doc that i received from DataLogic. 

From the documentation you can see that it says that it requires hardware handshaking so I have replaced 

`this._serialPort.RtsEnable = true;`
`this._serialPort.DtrEnable = true;`

with
`this._serialPort.Handshake = Handshake.RequestToSend;`

Please see [PR](https://github.com/brendangooden/datalogic-magellan-dotnet/pull/4) - I have created a new release and also pushed to Nuget `v1.0.2` - please check it and let me know if it works for you. 

Please note that this is only tested/certified for use with 9xxx series e.g. 9800 / 9300. Can you confirm what scale model you are using?

**Comment by TheDelus** [comment]
Hi @brendangooden  
I cant find the scanner scale protocol summary. Where is it? Can you add it to the repo?

**Comment by brendangooden** [comment]
@TheDelus Sorry here it is. 
[Scanner Scale Protocol Summary.zip](https://github.com/brendangooden/datalogic-magellan-dotnet/files/11322346/Scanner.Scale.Protocol.Summary.zip)

**Comment by brendangooden** [comment]
Hi @TheDelus  Did the new update fix the issue for you?

**Comment by TheDelus** [comment]
Hi, yes I can confirm that its working. It is even working with a Datalogic 8400 Scanner/Scale.
